name: Periodic Backstage.io docker image build

env:
  BACKSTAGE_GITHUB_ORG: backstage
  BACKSTAGE_GITHUB_REPO: backstage
  REGISTRY: ghcr.io
  IMAGE_NAME: backstairs/backstage

on:
  workflow_dispatch:
  schedule:
    - cron:  '33 5,17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get the latest release version
        id: get_backstage_version
        run: |
          release_version=$(curl -s "https://api.github.com/repos/${BACKSTAGE_GITHUB_ORG}/${BACKSTAGE_GITHUB_REPO}/releases/latest" | grep \"name\"  | sed -n 's/.*\"name\": "\(release-\)*\([^"]*\)",/\2/p')
          echo ::set-output name=release_version::${release_version:-2021-11-17}
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Dump metadata context and version
        env:
          META_OUTPUT: ${{ toJson(steps.meta.outputs) }}
        run: echo "$META_OUTPUT ; echo ${{ steps.get_backstage_version.outputs.release_version }}"
      - name: Get current image
        id: get_docker_image_version
        run: |
          docker run --rm quay.io/skopeo/stable list-tags docker://ghcr.io/$IMAGE_NAME
